In [2]:
import pandas as pd 
import numpy as np 
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

loading the data

In [3]:
raw_df = pd.read_csv("../data/train_data/train_data.csv")

In [4]:
raw_df.head(10)

   event_id  time_to_tca  mission_id       risk  ...   F10   F3M   SSN    AP
0         0     1.566798           5 -10.204955  ...  89.0  83.0  42.0  11.0
1         0     1.207494           5 -10.355758  ...  89.0  83.0  42.0  11.0
2         0     0.952193           5 -10.345631  ...  89.0  83.0  42.0  11.0
3         0     0.579669           5 -10.337809  ...  89.0  83.0  40.0  14.0
4         0     0.257806           5 -10.391260  ...  89.0  83.0  40.0  14.0
5         1     6.530455           5  -7.561299  ...  71.0  88.0   0.0   2.0
6         1     5.561646           5  -9.315693  ...  70.0  87.0  13.0  14.0
7         1     5.226504           5  -7.422508  ...  70.0  87.0  13.0  14.0
8         1     3.570013           5  -9.248105  ...  71.0  87.0  21.0   5.0
9         2     6.983474           2 -10.816161  ...  73.0  77.0  27.0   4.0

[10 rows x 103 columns]

printing the columns of the data

In [5]:
col_list = []
for column in raw_df.columns:
    col_list = np.append(col_list, column) 

print(col_list)

['event_id' 'time_to_tca' 'mission_id' 'risk' 'max_risk_estimate'
 'max_risk_scaling' 'miss_distance' 'relative_speed' 'relative_position_r'
 'relative_position_t' 'relative_position_n' 'relative_velocity_r'
 'relative_velocity_t' 'relative_velocity_n' 't_time_lastob_start'
 't_time_lastob_end' 't_recommended_od_span' 't_actual_od_span'
 't_obs_available' 't_obs_used' 't_residuals_accepted' 't_weighted_rms'
 't_rcs_estimate' 't_cd_area_over_mass' 't_cr_area_over_mass' 't_sedr'
 't_j2k_sma' 't_j2k_ecc' 't_j2k_inc' 't_ct_r' 't_cn_r' 't_cn_t'
 't_crdot_r' 't_crdot_t' 't_crdot_n' 't_ctdot_r' 't_ctdot_t' 't_ctdot_n'
 't_ctdot_rdot' 't_cndot_r' 't_cndot_t' 't_cndot_n' 't_cndot_rdot'
 't_cndot_tdot' 'c_object_type' 'c_time_lastob_start' 'c_time_lastob_end'
 'c_recommended_od_span' 'c_actual_od_span' 'c_obs_available' 'c_obs_used'
 'c_residuals_accepted' 'c_weighted_rms' 'c_rcs_estimate'
 'c_cd_area_over_mass' 'c_cr_area_over_mass' 'c_sedr' 'c_j2k_sma'
 'c_j2k_ecc' 'c_j2k_inc' 'c_ct_r' 'c_cn_r' 'c_cn_t' 'c_crdot_r'
 'c_crdot_t' 'c_crdot_n' 'c_ctdot_r' 'c_ctdot_t' 'c_ctdot_n'
 'c_ctdot_rdot' 'c_cndot_r' 'c_cndot_t' 'c_cndot_n' 'c_cndot_rdot'
 'c_cndot_tdot' 't_span' 'c_span' 't_h_apo' 't_h_per' 'c_h_apo' 'c_h_per'
 'geocentric_latitude' 'azimuth' 'elevation' 'mahalanobis_distance'
 't_position_covariance_det' 'c_position_covariance_det' 't_sigma_r'
 'c_sigma_r' 't_sigma_t' 'c_sigma_t' 't_sigma_n' 'c_sigma_n'
 't_sigma_rdot' 'c_sigma_rdot' 't_sigma_tdot' 'c_sigma_tdot'
 't_sigma_ndot' 'c_sigma_ndot' 'F10' 'F3M' 'SSN' 'AP']

looking at the data  
A single event_id might have multiple rows leading up to the exact moment they cross paths.

In [6]:
# extracting the target feature 

df_sorted = raw_df.sort_values(by=['event_id', 'time_to_tca'], ascending=[True, False])

final_cdms = df_sorted.groupby('event_id').last().reset_index()

# creating the target labels
targets = final_cdms[['event_id', 'risk']].copy()
targets['is_hazard'] = (targets['risk'] >= -4.0).astype(int)

# Filter for all messages issued at least 2 days before the collision
df_early = df_sorted[df_sorted['time_to_tca'] >= 2.0]

features = df_early.groupby('event_id').last().reset_index()

master_df = pd.merge(features, targets[['event_id', 'is_hazard']], on='event_id')

In [7]:
display(master_df['is_hazard'].value_counts())

is_hazard
0    11931
1       11
Name: count, dtype: int64

thats an insane imbalance :)

after the sorting we must choose the columns we want in our data set and drop the rest to reduce the noise  
next is feature selection

In [8]:
# the model cant understand coordinate features like the position, velocity vectors and angles so...
# we will turn the vectors into distance and speed but "miss_distance", "relative_speed" already exist so the vectors will just get dropped

clean_df = master_df.drop(['relative_position_r',
                            'relative_position_t', 'relative_position_n', 'relative_velocity_r',
                            'relative_velocity_t', 'relative_velocity_n'], axis=1)

In [9]:
# the angles 'geocentric_latitude', 'azimuth', 'elevation' and 'x_j2k_inc' are turned into sin and cos

# clean_df[['geocentric_latitude_rad', 'azimuth_rad', 'elevation_rad', 't_j2k_inc_rad', 'c_j2k_inc_rad']] = np.radians(clean_df[['geocentric_latitude', 'azimuth', 'elevation', 't_j2k_inc', 'c_j2k_inc']])
# clean_df[['geocentric_latitude_sin', 'azimuth_sin', 'elevation_sin', 't_j2k_inc_sin', 'c_j2k_inc_sin']] = np.sin(clean_df[['geocentric_latitude_rad', 'azimuth_rad', 'elevation_rad', 't_j2k_inc_rad', 'c_j2k_inc_rad']])
# clean_df[['geocentric_latitude_cos', 'azimuth_cos', 'elevation_cos', 't_j2k_inc_cos', 'c_j2k_inc_cos']] = np.cos(clean_df[['geocentric_latitude_rad', 'azimuth_rad', 'elevation_rad', 't_j2k_inc_rad', 'c_j2k_inc_rad']])

# clean_df = clean_df.drop(['geocentric_latitude', 'azimuth', 'elevation', 't_j2k_inc', 'c_j2k_inc', 'geocentric_latitude_rad', 'azimuth_rad', 'elevation_rad', 't_j2k_inc_rad', 'c_j2k_inc_rad'], axis=1)

angles = ['geocentric_latitude', 'azimuth', 'elevation', 't_j2k_inc', 'c_j2k_inc']
for col in angles:
    clean_df[f'{col}_sin'] = np.sin(np.radians(clean_df[col]))
    clean_df[f'{col}_cos'] = np.cos(np.radians(clean_df[col]))
    clean_df = clean_df.drop(columns=[col])

In [10]:
# now looking at the data set most of the features left are noise and must be dropped 

# after sorting and extracting the target these features will cause data leakage if not dropped
leakage_features = ['event_id', 'mission_id', 'risk', 'max_risk_estimate', 'max_risk_scaling']
clean_df = clean_df.drop(leakage_features, axis= 1)      

# the model doesn't care about the probabilities of the radar so all the radar meta data will be dropped
meta_cols = [col for col in clean_df.columns if 'lastob' in col or 'obs_' in col or 'residuals' in col or 'od_span' in col or 'rms' in col]
clean_df = clean_df.drop(columns= meta_cols)

# now dropping all the cross sectional correlations 
cross_terms = [col for col in clean_df.columns if (col.startswith('t_c') or col.startswith('c_c')) and 'type' not in col and 'span' not in col and 'covariance' not in col]
clean_df = clean_df.drop(columns=cross_terms, errors='ignore')

# dropping the left un needed columns
clean_df = clean_df.drop(columns= ["time_to_tca"])

In [11]:
col_list = []
for column in clean_df.columns:
    col_list = np.append(col_list, column) 

print(col_list)

['miss_distance' 'relative_speed' 't_rcs_estimate' 't_sedr' 't_j2k_sma'
 't_j2k_ecc' 'c_object_type' 'c_rcs_estimate' 'c_sedr' 'c_j2k_sma'
 'c_j2k_ecc' 't_span' 'c_span' 't_h_apo' 't_h_per' 'c_h_apo' 'c_h_per'
 'mahalanobis_distance' 't_position_covariance_det'
 'c_position_covariance_det' 't_sigma_r' 'c_sigma_r' 't_sigma_t'
 'c_sigma_t' 't_sigma_n' 'c_sigma_n' 't_sigma_rdot' 'c_sigma_rdot'
 't_sigma_tdot' 'c_sigma_tdot' 't_sigma_ndot' 'c_sigma_ndot' 'F10' 'F3M'
 'SSN' 'AP' 'is_hazard' 'geocentric_latitude_sin'
 'geocentric_latitude_cos' 'azimuth_sin' 'azimuth_cos' 'elevation_sin'
 'elevation_cos' 't_j2k_inc_sin' 't_j2k_inc_cos' 'c_j2k_inc_sin'
 'c_j2k_inc_cos']

In [12]:
clean_df

       miss_distance  relative_speed  ...  c_j2k_inc_sin  c_j2k_inc_cos
0            26899.0          3434.0  ...       0.991288       0.131711
1            18763.0         14347.0  ...       0.938001       0.346633
2            23900.0         13574.0  ...       0.944791       0.327675
3            33593.0         12093.0  ...       0.988074       0.153979
4              304.0          2001.0  ...       0.990740      -0.135774
...              ...             ...  ...            ...            ...
11937         8239.0         12150.0  ...       0.121008       0.992651
11938         3569.0         14952.0  ...       0.960993       0.276574
11939        34897.0         11876.0  ...       0.961256       0.275658
11940        24921.0          1156.0  ...       0.987980      -0.154582
11941         2257.0         14976.0  ...       0.998117       0.061331

[11942 rows x 47 columns]

turning the multiclass type feature into binary features that the model can understand

In [13]:
df_final = pd.get_dummies(clean_df, columns=['c_object_type'])

printing all the hazards

In [14]:
single_event = df_final[clean_df['is_hazard'] == 1] # Or whatever the first ID is
display(single_event)

       miss_distance  relative_speed  ...  c_object_type_TBA  c_object_type_UNKNOWN
1046           119.0         14985.0  ...              False                  False
4710           352.0         14983.0  ...              False                  False
5236          1827.0           212.0  ...              False                  False
5744           492.0          4132.0  ...              False                   True
7956           216.0         14940.0  ...              False                  False
8204            67.0         14768.0  ...              False                   True
8484          3926.0         14562.0  ...              False                   True
8503           251.0         13342.0  ...              False                   True
10143         9364.0         14724.0  ...              False                  False
11355          473.0         14695.0  ...              False                  False
11398          546.0         14954.0  ...              False                   True

[11 rows x 51 columns]

4 of the 11 hazards has missing values so dropping the NA is not an option so we will instead use the median

In [15]:
X_full = df_final.drop(columns=['is_hazard'])
y_full = df_final['is_hazard']

In [16]:
X_train, X_val, y_train, y_val = train_test_split(X_full, y_full, test_size=.2, stratify=y_full, random_state=42)

In [17]:
X_train = X_train.fillna(X_train.median())
X_val = X_val.fillna(X_val.median())

In [18]:
scaler = StandardScaler()
X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train), columns=X_train.columns)
X_val_scaled = pd.DataFrame(scaler.transform(X_train), columns=X_val.columns)

In [19]:
smote = SMOTE(random_state=42)
X_train_balanced, y_train_balanced = smote.fit_resample(X_train_scaled, y_train)

In [21]:
display(y_train_balanced.value_counts())
display(y_val.value_counts())

is_hazard
0    9544
1    9544
Name: count, dtype: int64

is_hazard
0    2387
1       2
Name: count, dtype: int64

now that the data is cleaned, scaled and sampled the next step is modeling

In [24]:
X_train_final = X_train_balanced.to_csv("../data/clean_data/X_train_final", index=False)
X_val_final = X_val.to_csv("../data/clean_data/X_val_final", index=False)
y_train_final = y_train_balanced.to_csv("../data/clean_data/y_train_final", index=False)
y_val_final = y_val.to_csv("../data/clean_data/y_val_final", index=False)